server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/employee/**
#          filters:
#            - CustomFilter
#            - name: Hystrix
#              args:
#                name: fallbackCommand
#                fallbackUri: forward:/fallback/message
        - id: consumerModule
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/consumer/**
#          filters:
#            - CustomFilter
#            - name: Hystrix
#              args:
#                name: fallbackCommand
#                fallbackUri: forward:/fallback/message
      default-filters:
        - name: CustomFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
