server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/consumer/**
      default-filters:
        - name: CustomFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
